version: '3'

services:

  webserver:
    build:
      context: ./env/etc/webserver
    container_name: 'webserver'
    restart: 'always'
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 10000:10000
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www
      - ${PHP_INI_DIR-./env/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./env/config/vhosts}:/etc/apache2/sites-enabled
      - ${SSL_DIR-./env/config/ssl}:/etc/apache2/ssl/
      - ${APACHE_LOG_DIR-./env/logs/apache2}:/var/log/apache2

  mysql:
    build:
      context: ./env/etc/mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./env/logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-'secret'}
      MYSQL_DATABASE: ${MYSQL_DATABASE-'test'}
      MYSQL_USER: ${MYSQL_USER-'user'}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-'secret'}